spring:
  profiles:
    active: production
  application:
    name: datalog-api

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8081

---
spring:
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017
      database: dataLogging
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

---
spring:
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: dataLogging
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cucumberTest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/default

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dataLogging
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com