spring:
  profiles:
    active: production
  application:
    name: datalog-api

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8081

logging:
  file:
    name: logs/datalog-api/datalog-api.log
  logback:
    rollingpolicy:
      max-history: 7
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz

---
spring:
  config:
    activate:
      on-profile: production
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: dataLogging
okta:
  oauth2:
    issuer: https://dev-7pr07becg7e5y37g.us.auth0.com/
    audience: https://datalog-api-uonahdb5jq-uc.a.run.app

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: cucumberTest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/default

---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: dataLogging
okta:
  oauth2:
    issuer: https://dev-7pr07becg7e5y37g.us.auth0.com/
    audience: http://localhost:8080